#ifndef TOKEN_H
#define TOKEN_H

#include <string>

enum TokenType {
    COMANDO, IDENTIFICADOR, NUMERO, OPERADOR, FUNCAO, PARENTESIS_ESQUERDO, PARENTESIS_DIREITO,
    VIRGULA, FIM_DE_LINHA, NUMERO_LINHA, CHAVE_DIREITA, CHAVE_ESQUERDA, ASPAS_DUPLAS, LITERAL_TEXTO
};

struct Token {
    TokenType type;
    std::string value;
};

#endif // TOKEN_H